apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: chatbot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
        - name: chatbot
          image: jayesh9999/mental_health_assistant:latest
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: DB_HOST

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: chatbot-config
                  key: DB_NAME

            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: DB_USER

            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: DB_PASS

            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: GOOGLE_API_KEY
                   
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: chatbot-secret
                  key: SECRET_KEY   

